### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by plumcraft** [ianperrin/MMM-NetworkScanner#1]
Hello,

Thanks for your module, i've tried your config file but i got some syntax issues.
I've change ";" by "," when necessary and it works now :

Here my config file :
{
      module: 'MMM-NetworkScanner',
      position: 'top_left',
      config: {
        devices: [
                { macAddress: "1a:1b:1c:1a:1b:1c", name: "Server", icon: "server"},
                { macAddress: "2a:2b:2c:2a:2b:2c", name: "Desktop", icon: "desktop"},
                { macAddress: "3a:3b:3c:3a:3b:3c", name: "Laptop", icon: "laptop"},
                { macAddress: "4a:4b:4c:4a:4b:4c", name: "Laptop", icon: "laptop"}
            ],
        showUnknown: false,
        showOffline: true,
        keepAlive: 300,
        updateInterval: 5
      }
    }

**Comment by ianperrin** [comment]
Great pick up @plumcraft  - I've updated the example in the ReadMe file
