### ISSUE TITLE
IpAddress does not work

### ISSUE THREAD

**Issue by arx237** [ianperrin/MMM-NetworkScanner#13]
Mac address works fine however IP Address always shows offline no matter what. Ip address input as fqdn and as ip address.

**Comment by looolz** [comment]
I can't get neither IP (with IP or fully qualified host name) or MAC-addr working. All devices appear as offline. The Pi is however able to find said devices using ping.

**Comment by ToddKlindt** [comment]
I have the same issue. IP address never works, MAC always works.

**Comment by nawak86** [comment]
hello no solution for this problem ?
ty

**Comment by ianperrin** [comment]
After some time in the wilderness, I have found a little time to review the state of this module. To kick off, I have pushed a series of updates to the repository as an initial attempt to introduce some fixes - including some work on the **ipaddress** issue. Please feel free to pull these changes and test in your mirror. 

If you continue to have issues with the IpAddress not working, please provide as much info as possible below, including a description of the problem, what you were expecting to happen, the config for the module and any errors from the log and/or browser console.
