### ISSUE TITLE
Not finding android phone in sleep

### ISSUE THREAD

**Issue by smartroad** [ianperrin/MMM-NetworkScanner#15]
I have been trying to get this to monitor my mobile phone (Android v7). It finds my phone but only when the screen is on. Once the screen is off it no longer finds my phone. This is probably an issue with the way Android handles WiFi. I have set WiFi to stay on in standby with the phone though and I can ping it via the raspberry pi running my magic mirror.

I was hoping to use this so me and the other half can know if the other is home :)

**Comment by ianperrin** [comment]
In theory the `keepAlive` config option can be used to cater for these situations - have you tried using this?
