### ISSUE TITLE
Needs MM2 to run as "root"?

### ISSUE THREAD

**Issue by Snille** [ianperrin/MMM-NetworkScanner#2]
Hi, I'm currently testing this out on a normal Ubuntu Server 14.04.5 as serveronly install.
It seems that the NetworkScanner module only works if I run MM with sudo "sudo node serveronly".
If I don't do that I only get "Loading..." on the module.
Is there anything I can do to not need to run MM as root?

Best regards Erik

**Comment by ianperrin** [comment]
@Snille - running MM2 as root should not be required to make the module work. Is there any information in the logs which may help the investigation.

**Comment by Snille** [comment]
@ianperrin In what log should I be looking? :) Is there a specific one for MM2? Or for the module? I'm fairly new to the MM2 ecosystem.

**Comment by ianperrin** [comment]
@Snille as you are running MM2 using `node serveronly` then you will see information appear in two places
1. the terminal/command prompt where you ran the command
2. The javascript console in your browser (see http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers#77337)

**Comment by Snille** [comment]
@ianperrin I moved over MM2 to run with root anyway (because that's going to be the way I will run it on the RPi anyway later on). So you can close this case, I'll come back if it becomes a problem when I've moved over to the correct hardware. :)
