### ISSUE TITLE
Can't order the entries.

### ISSUE THREAD

**Issue by tomwoodhams** [ianperrin/MMM-NetworkScanner#21]
I want to to able to display the entries in the order they are configured, it seems to reorder them to be Alphabetical which is not great (for me!).  Is it possible to not Alphabetise them or be able to disable the sorting?

**Comment by ianperrin** [comment]
@tomwoodhams - I've just begun to revisit looking into this module, so your suggestion was timely.

There's quite a lot of work which needs to be done to refactor and address several issues with the codebase. 

However, the latest version, which I've just published does include initial support for disabling device sorting by updating to the latest version, adding `sort: false,` to the config options and restarting the mirror.

Let me know how you get on
