### ISSUE TITLE
How to specify font icons

### ISSUE THREAD

**Issue by E3V3A** [ianperrin/MMM-NetworkScanner#24]
Where can I find a list of available icons?

**Comment by ToddKlindt** [comment]
I believe it uses the "Font Awesome" icons. Doing a search on that should give you the list of icons it supports. Some of the icon names start with "fa-" I think you can skip that when you define the icon name in the config.js file.

**Comment by E3V3A** [comment]
Yeah, thanks, I found some of those [here](https://origin.fontawesome.com/icons?d=gallery&m=free). Perhaps give a short list of common ones for users to get started with. 
Now I have and use: 
```
globe
server
print
laptop
tv
mobile
tablet
```

**Comment by ianperrin** [comment]
@E3V3A - I've updated the readme file to provide more information about the [device object](https://github.com/ianperrin/MMM-NetworkScanner#device-object) - including the `icon` option. Hope this helps.
