### ISSUE TITLE
How to use the network option

### ISSUE THREAD

**Issue by E3V3A** [ianperrin/MMM-NetworkScanner#26]
The readme says: `network  "-l"`... (Is hard to tell if it is an uppercase `i` or a lower case `L`!) 
It's a lowercase L.   
But how to use that option and when?

man pages for arp-scan:

>  --localnet or -l
>  Generate addresses from network interface configuration.  Use the network interface IP address and network mask to generate the list of target host addresses.  The list will include  the  network  and  broadcast  addresses,  so an interface address of 10.0.0.1 with netmask 255.255.255.0 would generate 256 target hosts from 10.0.0.0 to 10.0.0.255 inclusive.  If you use this option, you cannot specify the --file option or specify any target hosts on the command line.  The interface specifications are  taken  from  the interface that arp-scan will use, which can be changed with the --interface option.

**Comment by ianperrin** [comment]
@E3V3A - I've tweaked the description for the `network` option to clarify the use of `-l`

This option was introduced to address a particular need (#9) and can generally be omitted.
