### ISSUE TITLE
columns are misaligned depending on module positions top_right or top_left

### ISSUE THREAD

**Issue by E3V3A** [ianperrin/MMM-NetworkScanner#30]
The columns are misaligned depending if the module position is on left or right side  (e.g. `top_right` or `top_left`). Ideally there should be a CSS left justification somewhere in the DOM. (And right just for 3rd and last column.)

Also need column space when last seen not enabled/available. 
Related to #29

**Comment by E3V3A** [comment]
The best solution is probably to add a CSS file, and make sure we have 3 columns.

**Comment by ianperrin** [comment]
@E3V3A - 1a89250 (on the develop branch) contains an initial fix for the alignment issues. Could you test and confirm it works as expected?

````
cd ~/MagicMirror/modules/MMM-NetworkScanner
git checkout --track origin/develop
````

**Comment by E3V3A** [comment]
Great! Yeah, that seem to work! :+1:

**Comment by ianperrin** [comment]
Thanks @E3V3A - [v0.0.4](/ianperrin/MMM-NetworkScanner/releases/tag/v0.0.4) has been published - you may want to switch back to the master branch again:
````
cd ~/MagicMirror/modules/MMM-NetworkScanner
git checkout master
````
