### ISSUE TITLE
Improvement request: Add CSS to control module formatting

### ISSUE THREAD

**Issue by E3V3A** [ianperrin/MMM-NetworkScanner#31]
I'd like to use this module as part of a more general MM info page, but the current DOM does not look good when module is moved around or on the right side, for example. I would very much like to see a CSS file connected with this module so that:

- [x] 1. You can left/right align each of the 3 fields (icon, device name, last seen info)
- [x] 2. Make the fields into aligned columns, perhaps: `LLR`
- [x] 3. Allow for easy change of font size and color

**Comment by ianperrin** [comment]
@E3V3A - 1a89250 (on the develop branch) adds a css file and changes to the DOM as an initial fix for the alignment issues. Could you test and confirm it works as expected?

````
cd ~/MagicMirror/modules/MMM-NetworkScanner
git checkout --track origin/develop
````

Font size and color styling should be possible by adding rules to the `custom.css`

**Comment by E3V3A** [comment]
look good

**Comment by ianperrin** [comment]
Thanks @E3V3A - [v0.0.4](/ianperrin/MMM-NetworkScanner/releases/tag/v0.0.4) has been published - you may want to switch back to the master branch again:
````
cd ~/MagicMirror/modules/MMM-NetworkScanner
git checkout master
````
