### ISSUE TITLE
issue running ./arps2mm.sh script

### ISSUE THREAD

**Issue by ElecTechAce** [ianperrin/MMM-NetworkScanner#39]
no matter which way I try I'm unable to run the script. I keep getting permission denied even as sudo. please help

$ ./arps2mm.sh
-bash: ./arps2mm.sh: Permission denied

sudo ./arps2mm.sh
sudo: ./arps2mm.sh: command not found

**Comment by ianperrin** [comment]
Hi @ElecTechAce 

Could you try running the following and see if that helps?
````
cd ~/MagicMirror/modules/MMM-NetworkScanner/scripts
chmod +x arps2mm.sh
./arps2mm.sh
````

**Comment by ElecTechAce** [comment]
got it. thank you so much
