### ISSUE TITLE
Uncaught TypeError: Cannot read property 'notification' of null

### ISSUE THREAD

**Issue by bogomips** [ianperrin/MMM-NetworkScanner#44]
This occurs in a particular case:

- this.config.residents.length > 0
- anyoneHome == 0
- this.occupied === true
- the user does not set vacantCMD, 
   command = self.config.vacantCMD; // `command` is null
---> https://github.com/ianperrin/MMM-NetworkScanner/blob/master/MMM-NetworkScanner.js#L152
---> https://github.com/ianperrin/MMM-NetworkScanner/blob/master/MMM-NetworkScanner.js#L153 <-- here  the execption occurs

A possible trivial fix:
`
if (command)
   this.sendNotification(command.notification, command.payload);
`

**Comment by ianperrin** [comment]
@bogomips - a more long term fix might be to implement some form of config validation, but for now I’ll implement your proposed change.
