### ISSUE TITLE
Stuck Loading

### ISSUE THREAD

**Issue by aareben** [ianperrin/MMM-NetworkScanner#53]
I just installed this module and I can't seem to get it to scan. Am I doing something wrong? I specifically assigned IP addresses to each phone.

		{
       			module: 'MMM-NetworkScanner',
        		position: 'top_left', 
        		config: {
            			devices:[
                    			{ ipAddress: "192.168.1.**", name: "Sister", icon: "fas fa-female"},
                    			{ ipAddress: "192.168.1.**", name: "Mom", icon: "fas fa-female"},
					{ ipAddress: "192.168.1.**", name: "Dad", icon: "fas fa-male"},
                			]
        			}        
    		},

**Comment by salco** [comment]
@aareben look at your logs I think it's linked to the fact that you need sudo permission to execute this module.
