### ISSUE TITLE
Duplicate item entries

### ISSUE THREAD

**Issue by jaolstad** [ianperrin/MMM-NetworkScanner#7]
In the latest release all network items appears twice, independent of their status. Am I doing something wrong in my config, or is this a known bug?

**Comment by ianperrin** [comment]
@jaolstad - this issue began to occur when support for scanning was introduced. A fix has been applied which should fix it. Could you pull the latest version and confirm?

**Comment by jaolstad** [comment]
Issue fixed, thanks!
